"""rename task assignee

Revision ID: b59cbf36df03
Revises: 799df3ddd77f
Create Date: 2026-08-21 12:37:41.549887

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b59cbf36df03"
down_revision: Union[str, Sequence[str], None] = "799df3ddd77f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("task_asignees", "task_assignees")
    op.execute(
        "ALTER INDEX ix_task_asignees_user_id " "RENAME TO ix_task_assignees_user_id"
    )
    op.execute(
        "ALTER TABLE task_assignees "
        "RENAME CONSTRAINT task_asignees_pkey "
        "TO task_assignees_pkey"
    )
    op.execute(
        "ALTER TABLE task_assignees "
        "RENAME CONSTRAINT task_asignees_task_id_fkey "
        "TO task_assignees_task_id_fkey"
    )
    op.execute(
        "ALTER TABLE task_assignees "
        "RENAME CONSTRAINT task_asignees_user_id_fkey "
        "TO task_assignees_user_id_fkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER INDEX ix_task_assignees_user_id " "RENAME TO ix_task_asignees_user_id"
    )
    op.execute(
        "ALTER TABLE task_assignees "
        "RENAME CONSTRAINT task_assignees_pkey "
        "TO task_asignees_pkey"
    )
    op.execute(
        "ALTER TABLE task_assignees "
        "RENAME CONSTRAINT task_assignees_task_id_fkey "
        "TO task_asignees_task_id_fkey"
    )
    op.execute(
        "ALTER TABLE task_assignees "
        "RENAME CONSTRAINT task_assignees_user_id_fkey "
        "TO task_asignees_user_id_fkey"
    )
    op.rename_table("task_assignees", "task_asignees")
    # ### end Alembic commands ###
